server:
  port: 8081
  servlet:
    context-path: /luckymoney
#limit对象，有三个字段
limit:
  minMoney: 0.01
  maxMoney: 9999
  description: 最少要发${limit.minMoney}元，最多${limit.maxMoney}元
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/luckymoney?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    hibernate:
#      由实体类自动创建表
#      ddl-auto: create
      ddl-auto: update
    show-sql: true
